//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        [Required]
        [Display(Name = "Vehicle Name")]

        public Nullable<int> VehicleId { get; set; }
        [Required]
        [Display(Name = "Customer Name")]

        public Nullable<int> CustomerID { get; set; }
        [Required]
        [Display(Name = "Order Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Required]
        [Display(Name = "No of Item")]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> QTY { get; set; }
        [Required]
        [Display(Name = "Total Price")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> TotalPrice { get; set; }

    
        public virtual Customer Customer { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
